const ONLINE = {
  SUPABASE_URL: 'https://mfqihieztxqhgxzvdrii.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mcWloaWV6dHhxaGd4enZkcmlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTE0OTAyOTIsImV4cCI6MjEwNzA2NjI5Mn0.5tJq5_fhqcfqVeuNtBPtl1yPHBDs8IupOnaqIhtfITQ',
