name: Unzip Archive
on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Extract zip file
        run: |
          unzip drift-kings.zip -d main/
          rm drift-kings.zip
          
      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m "Automated unzip into main directory" || echo "No changes to commit"
          git push origin main
